# -*- coding: utf-8 -*-
"""ensemble pareado

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dat4bThYp8LH8AOSHBml1MiB-y9d9QNr
"""

import re
import json
import random
from pathlib import Path

import numpy as np
import pandas as pd
import nltk

from scipy.sparse import vstack

from sklearn.pipeline import FeatureUnion
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

SEED = 40

TRAIN_PATH = Path("corpus/train.jsonl")
VALIDATION_PATH = Path("corpus/validation.jsonl")
TEST_PATH = Path("corpus/test.jsonl")

NON_PUN_LABEL = 0
PUN_LABEL = 1

random.seed(SEED)
np.random.seed(SEED)

def load_jsonl(file_path):
    rows = []

    with open(file_path, "r", encoding="utf-8") as file:
        for line in file:
            if line.strip():
                rows.append(json.loads(line))

    return pd.DataFrame(rows)


train_df = load_jsonl(TRAIN_PATH)
validation_df = load_jsonl(VALIDATION_PATH)
test_df = load_jsonl(TEST_PATH)

print("Train shape:", train_df.shape)
print("Validation shape:", validation_df.shape)
print("Test shape:", test_df.shape)

display(train_df.head())
display(validation_df.head())
display(test_df.head())

required_columns = {"id", "text", "label"}

for split_name, dataframe in [
    ("train", train_df),
    ("validation", validation_df),
    ("test", test_df)
]:
    missing_columns = required_columns - set(dataframe.columns)

    if missing_columns:
        raise ValueError(f"Missing columns in {split_name}: {missing_columns}")

    dataframe["id"] = dataframe["id"].astype(str)
    dataframe["text"] = dataframe["text"].astype(str)
    dataframe["label"] = dataframe["label"].astype(int)

    invalid_labels = set(dataframe["label"].unique()) - {0, 1}

    if invalid_labels:
        raise ValueError(f"Invalid labels in {split_name}: {invalid_labels}")

print("Train label distribution:")
display(train_df["label"].value_counts().sort_index())

print("Validation label distribution:")
display(validation_df["label"].value_counts().sort_index())

print("Test label distribution:")
display(test_df["label"].value_counts().sort_index())

def extract_pair_id(example_id):
    return re.sub(r"\.[HN]$", "", str(example_id))


def extract_pair_suffix(example_id):
    match = re.search(r"\.([HN])$", str(example_id))

    if match:
        return match.group(1)

    return None


for dataframe in [train_df, validation_df, test_df]:
    dataframe["pair_id"] = dataframe["id"].apply(extract_pair_id)
    dataframe["pair_suffix"] = dataframe["id"].apply(extract_pair_suffix)


print("Train suffix vs label:")
display(pd.crosstab(train_df["pair_suffix"], train_df["label"]))

print("Validation suffix vs label:")
display(pd.crosstab(validation_df["pair_suffix"], validation_df["label"]))

print("Test suffix vs label:")
display(pd.crosstab(test_df["pair_suffix"], test_df["label"]))

def validate_complete_pairs(dataframe, split_name):
    pair_sizes = dataframe.groupby("pair_id").size()
    invalid_size_pairs = pair_sizes[pair_sizes != 2]

    if len(invalid_size_pairs) > 0:
        display(invalid_size_pairs.head(20))
        raise ValueError(
            f"{split_name}: {len(invalid_size_pairs)} pairs do not have exactly 2 examples."
        )

    invalid_label_pairs = []

    for pair_id, group in dataframe.groupby("pair_id"):
        labels = set(group["label"].tolist())

        if labels != {NON_PUN_LABEL, PUN_LABEL}:
            invalid_label_pairs.append(pair_id)

    if len(invalid_label_pairs) > 0:
        raise ValueError(
            f"{split_name}: {len(invalid_label_pairs)} pairs do not have exactly one 0 and one 1."
        )

    print(f"{split_name}: valid pairs.")
    print(f"{split_name}: {len(pair_sizes)} pairs, {len(dataframe)} examples.")


validate_complete_pairs(train_df, "Train")
validate_complete_pairs(validation_df, "Validation")
validate_complete_pairs(test_df, "Test")

train_pair_ids = set(train_df["pair_id"])
validation_pair_ids = set(validation_df["pair_id"])
test_pair_ids = set(test_df["pair_id"])

train_validation_overlap = train_pair_ids.intersection(validation_pair_ids)
train_test_overlap = train_pair_ids.intersection(test_pair_ids)
validation_test_overlap = validation_pair_ids.intersection(test_pair_ids)

print("Train/validation pair overlap:", len(train_validation_overlap))
print("Train/test pair overlap:", len(train_test_overlap))
print("Validation/test pair overlap:", len(validation_test_overlap))

if train_validation_overlap or train_test_overlap or validation_test_overlap:
    raise ValueError("There is pair_id overlap between splits.")

print("OK: no pair_id overlap between train, validation and test.")

def build_unordered_pair_dataframe(dataframe):
    pair_rows = []

    for pair_id, group in dataframe.groupby("pair_id"):
        group = group.sort_values("id").reset_index(drop=True)

        if len(group) != 2:
            continue

        row_a = group.iloc[0]
        row_b = group.iloc[1]

        pair_rows.append({
            "pair_id": pair_id,

            "a_id": row_a["id"],
            "a_text": row_a["text"],
            "a_label": int(row_a["label"]),

            "b_id": row_b["id"],
            "b_text": row_b["text"],
            "b_label": int(row_b["label"])
        })

    return pd.DataFrame(pair_rows)


train_pairs_df = build_unordered_pair_dataframe(train_df)
validation_pairs_df = build_unordered_pair_dataframe(validation_df)
test_pairs_df = build_unordered_pair_dataframe(test_df)

print("Train pairs:", train_pairs_df.shape)
print("Validation pairs:", validation_pairs_df.shape)
print("Test pairs:", test_pairs_df.shape)

display(train_pairs_df.head())

feature_extractor = FeatureUnion([
    (
        "word_tfidf",
        TfidfVectorizer(
            analyzer="word",
            ngram_range=(1, 3),
            sublinear_tf=True,
            min_df=1,
            max_df=0.95,
            lowercase=True
        )
    ),
    (
        "char_tfidf",
        TfidfVectorizer(
            analyzer="char_wb",
            ngram_range=(3, 5),
            sublinear_tf=True,
            min_df=1,
            max_df=0.95,
            lowercase=True
        )
    )
])

feature_extractor

feature_extractor.fit(train_df["text"])

print("Feature extractor fitted.")

def build_pair_difference_dataset(pair_dataframe, feature_extractor):
    a_vectors = feature_extractor.transform(pair_dataframe["a_text"])
    b_vectors = feature_extractor.transform(pair_dataframe["b_text"])

    x_forward = a_vectors - b_vectors
    y_forward = pair_dataframe["a_label"].astype(int).to_numpy()

    x_backward = b_vectors - a_vectors
    y_backward = pair_dataframe["b_label"].astype(int).to_numpy()

    x_pair = vstack([x_forward, x_backward])
    y_pair = np.concatenate([y_forward, y_backward])

    return x_pair, y_pair


x_train_pair, y_train_pair = build_pair_difference_dataset(
    train_pairs_df,
    feature_extractor
)

x_validation_pair, y_validation_pair = build_pair_difference_dataset(
    validation_pairs_df,
    feature_extractor
)

print("Pair-difference train shape:", x_train_pair.shape)
print("Pair-difference validation shape:", x_validation_pair.shape)

print("Train pair labels:")
display(pd.Series(y_train_pair).value_counts().sort_index())

print("Validation pair labels:")
display(pd.Series(y_validation_pair).value_counts().sort_index())

lr_l2_model = LogisticRegression(
    random_state=SEED,
    max_iter=5000,
    C=1.0,
    class_weight="balanced",
    solver="liblinear"
)

lr_l1_model = LogisticRegression(
    random_state=SEED,
    max_iter=5000,
    C=0.5,
    penalty="l1",
    class_weight="balanced",
    solver="liblinear"
)

sgd_model = SGDClassifier(
    loss="log_loss",
    penalty="elasticnet",
    alpha=1e-4,
    l1_ratio=0.15,
    class_weight="balanced",
    random_state=SEED,
    max_iter=3000,
    tol=1e-4
)

svm_model = SVC(
    kernel="linear",
    C=1.0,
    probability=True,
    class_weight="balanced",
    random_state=SEED
)

pairwise_ensemble_model = VotingClassifier(
    estimators=[
        ("lr_l2", lr_l2_model),
        ("lr_l1", lr_l1_model),
        ("sgd", sgd_model),
        ("svm", svm_model)
    ],
    voting="soft",
    weights=[3, 2, 2, 2],
    n_jobs=1
)

pairwise_ensemble_model

pairwise_ensemble_model.fit(x_train_pair, y_train_pair)

print("Pairwise ensemble training finished.")

def build_single_pair_comparison_matrix(pair_dataframe, feature_extractor):
    a_vectors = feature_extractor.transform(pair_dataframe["a_text"])
    b_vectors = feature_extractor.transform(pair_dataframe["b_text"])

    x_pair_comparison = a_vectors - b_vectors
    y_first_is_pun = pair_dataframe["a_label"].astype(int).to_numpy()

    return x_pair_comparison, y_first_is_pun


x_validation_comparison, y_validation_first_is_pun = build_single_pair_comparison_matrix(
    validation_pairs_df,
    feature_extractor
)

validation_proba_first_is_pun = pairwise_ensemble_model.predict_proba(
    x_validation_comparison
)[:, 1]

validation_pair_predictions_df = validation_pairs_df.copy()
validation_pair_predictions_df["prob_a_is_pun"] = validation_proba_first_is_pun

display(validation_pair_predictions_df.head())

def find_best_pair_threshold(y_true_first_is_pun, probabilities, metric_name="accuracy"):
    thresholds = np.linspace(
        probabilities.min(),
        probabilities.max(),
        300
    )

    best_threshold = 0.5
    best_value = -1.0

    for threshold in thresholds:
        y_pred = (probabilities > threshold).astype(int)

        if metric_name == "accuracy":
            value = accuracy_score(y_true_first_is_pun, y_pred)
        elif metric_name == "f1_macro":
            value = f1_score(
                y_true_first_is_pun,
                y_pred,
                average="macro",
                zero_division=0
            )
        else:
            raise ValueError("metric_name must be 'accuracy' or 'f1_macro'.")

        if value > best_value:
            best_value = value
            best_threshold = threshold

    return best_threshold, best_value


best_pair_threshold, best_validation_pair_accuracy = find_best_pair_threshold(
    y_validation_first_is_pun,
    validation_proba_first_is_pun,
    metric_name="accuracy"
)

print("Best pair threshold:", best_pair_threshold)
print("Best validation pair accuracy:", f"{best_validation_pair_accuracy:.4f}")

def predict_items_from_pair_model(
    pair_dataframe,
    feature_extractor,
    pairwise_model,
    threshold
):
    x_pair_comparison, y_first_is_pun = build_single_pair_comparison_matrix(
        pair_dataframe,
        feature_extractor
    )

    probabilities = pairwise_model.predict_proba(x_pair_comparison)[:, 1]
    first_is_pun_predictions = (probabilities > threshold).astype(int)

    item_rows = []

    for index, row in pair_dataframe.reset_index(drop=True).iterrows():
        first_is_pun = int(first_is_pun_predictions[index])

        if first_is_pun == 1:
            a_prediction = PUN_LABEL
            b_prediction = NON_PUN_LABEL
        else:
            a_prediction = NON_PUN_LABEL
            b_prediction = PUN_LABEL

        item_rows.append({
            "pair_id": row["pair_id"],
            "id": row["a_id"],
            "text": row["a_text"],
            "label": int(row["a_label"]),
            "prediction": a_prediction,
            "prob_a_is_pun": probabilities[index]
        })

        item_rows.append({
            "pair_id": row["pair_id"],
            "id": row["b_id"],
            "text": row["b_text"],
            "label": int(row["b_label"]),
            "prediction": b_prediction,
            "prob_a_is_pun": probabilities[index]
        })

    predictions_df = pd.DataFrame(item_rows)

    return predictions_df

def compute_metrics(y_true, y_pred):
    return {
        "accuracy": accuracy_score(y_true, y_pred),
        "precision_macro": precision_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        ),
        "recall_macro": recall_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        ),
        "f1_macro": f1_score(
            y_true,
            y_pred,
            average="macro",
            zero_division=0
        ),
        "precision_weighted": precision_score(
            y_true,
            y_pred,
            average="weighted",
            zero_division=0
        ),
        "recall_weighted": recall_score(
            y_true,
            y_pred,
            average="weighted",
            zero_division=0
        ),
        "f1_weighted": f1_score(
            y_true,
            y_pred,
            average="weighted",
            zero_division=0
        )
    }


def compute_pair_metrics(predictions_df):
    pair_exact_results = []

    for pair_id, group in predictions_df.groupby("pair_id"):
        if len(group) != 2:
            continue

        pair_exact_correct = bool(
            (group["label"] == group["prediction"]).all()
        )

        pair_exact_results.append(pair_exact_correct)

    return {
        "pair_exact_accuracy": float(np.mean(pair_exact_results)) if pair_exact_results else 0.0,
        "evaluated_pairs": int(len(pair_exact_results))
    }


def print_metrics(title, metrics):
    print(title)
    print("=" * len(title))

    for metric_name, metric_value in metrics.items():
        if isinstance(metric_value, float):
            print(f"{metric_name}: {metric_value:.4f}")
        else:
            print(f"{metric_name}: {metric_value}")

validation_predictions_df = predict_items_from_pair_model(
    pair_dataframe=validation_pairs_df,
    feature_extractor=feature_extractor,
    pairwise_model=pairwise_ensemble_model,
    threshold=best_pair_threshold
)

validation_metrics = compute_metrics(
    validation_predictions_df["label"],
    validation_predictions_df["prediction"]
)

validation_metrics.update(
    compute_pair_metrics(validation_predictions_df)
)

print_metrics("Validation results - pairwise ensemble", validation_metrics)

display(validation_predictions_df.head())

test_predictions_df = predict_items_from_pair_model(
    pair_dataframe=test_pairs_df,
    feature_extractor=feature_extractor,
    pairwise_model=pairwise_ensemble_model,
    threshold=best_pair_threshold
)

test_metrics = compute_metrics(
    test_predictions_df["label"],
    test_predictions_df["prediction"]
)

test_metrics.update(
    compute_pair_metrics(test_predictions_df)
)

print_metrics("Test results - pairwise ensemble", test_metrics)

display(test_predictions_df.head())

print("=== Classification report: pairwise ensemble ===")
print(
    classification_report(
        test_predictions_df["label"],
        test_predictions_df["prediction"],
        labels=[0, 1],
        target_names=["0", "1"],
        digits=2,
        zero_division=0
    )
)

cm = confusion_matrix(
    test_predictions_df["label"],
    test_predictions_df["prediction"],
    labels=[0, 1]
)

cm_df = pd.DataFrame(
    cm,
    index=["true_0", "true_1"],
    columns=["pred_0", "pred_1"]
)

display(cm_df)